version: '3.8'

services:
  app:
    build: .
    container_name: tms_app
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_PASSWORD=secret
      - DB_NAME=task_management
    volumes:
      - ./logs:/var/www/html/logs
      - ./public:/var/www/html/public
      - ./api:/var/www/html/api
      - ./database:/var/www/html/database
      - ./vendor:/var/www/html/vendor
      - ./.env:/var/www/html/.env:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: mysql:8.0
    container_name: tms_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: task_management
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  db_data: 